name: expo-front-end
on: [pull_request]
jobs:
    preview:
        runs-on: macos-latest
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: Change Dir
              run: cd ./Application/Pawsitive-Studying

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: npm

            - name: 🏗 Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}
                  package-manager: npm

            - name: 📦 Install dependencies
              run: npm install

            - name: 🚀 Create preview
              uses: expo/expo-github-action/preview@v8
              with:
                  qr-target: expo-go
                  working-directory: ./Application/Pawsitive-Studying
                  # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
                  # Use your own, or keep the automatically infered branch name from `--auto`, when using different triggers.
                  command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}
